// <auto-generated />
using System;
using IntegraCompanies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegraCompanies.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegraCompanies.Data.Models.BillingReport", b =>
                {
                    b.Property<Guid>("BillingReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("BillingReportId");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BillingReport");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JurPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CompanyId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("JurPersonId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Company");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.CompanyMask", b =>
                {
                    b.Property<Guid>("CompanyMaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CompanyMaskId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Mask");

                    b.HasIndex("CompanyId", "Mask")
                        .IsUnique();

                    b.ToTable("CompanyMask");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.Connection", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsRazdel")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ConnectionId");

                    b.HasIndex("ConnectionServerId", "DatabaseName")
                        .IsUnique();

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.ConnectionServer", b =>
                {
                    b.Property<Guid>("ConnectionServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ConnectionServerId");

                    b.ToTable("ConnectionServer");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.JurPerson", b =>
                {
                    b.Property<Guid>("JurPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("JurPersonId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JurPerson");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.SmtpServer", b =>
                {
                    b.Property<Guid>("SmtpServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SmtpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("SmtpEnableSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SmtpServerId");

                    b.ToTable("SmtpServer");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fname")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Lname")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mname")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.Company", b =>
                {
                    b.HasOne("IntegraCompanies.Data.Models.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegraCompanies.Data.Models.JurPerson", "JurPerson")
                        .WithMany("Companys")
                        .HasForeignKey("JurPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("IntegraCompanies.Data.Models.CompanyCounter", "CompanyCounter", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DayReceivingBeg")
                                .HasColumnType("integer");

                            b1.Property<int>("DayReceivingEnd")
                                .HasColumnType("integer");

                            b1.Property<bool>("PU21Enabled")
                                .HasColumnType("boolean");

                            b1.HasKey("CompanyId");

                            b1.ToTable("CompanyCounter", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("IntegraCompanies.Data.Models.CompanyGis", "CompanyGis", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("DebtEnabled")
                                .HasColumnType("boolean");

                            b1.Property<int>("DebtProcessType")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("OrgPPAGUID")
                                .HasColumnType("uuid");

                            b1.HasKey("CompanyId");

                            b1.ToTable("CompanyGis", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("IntegraCompanies.Data.Models.CompanyKvitok", "CompanyKvitok", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("BillingReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FromAddress")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FromName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<bool>("KvitokEnabled")
                                .HasColumnType("boolean");

                            b1.Property<Guid?>("SmtpServerId")
                                .HasColumnType("uuid");

                            b1.HasKey("CompanyId");

                            b1.HasIndex("BillingReportId");

                            b1.HasIndex("SmtpServerId");

                            b1.ToTable("CompanyKvitok", (string)null);

                            b1.HasOne("IntegraCompanies.Data.Models.BillingReport", "BillingReport")
                                .WithMany()
                                .HasForeignKey("BillingReportId");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");

                            b1.HasOne("IntegraCompanies.Data.Models.SmtpServer", "SmtpServer")
                                .WithMany()
                                .HasForeignKey("SmtpServerId");

                            b1.Navigation("BillingReport");

                            b1.Navigation("SmtpServer");
                        });

                    b.Navigation("CompanyCounter")
                        .IsRequired();

                    b.Navigation("CompanyGis")
                        .IsRequired();

                    b.Navigation("CompanyKvitok")
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("JurPerson");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.CompanyMask", b =>
                {
                    b.HasOne("IntegraCompanies.Data.Models.Company", "Company")
                        .WithMany("CompanyMasks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.Connection", b =>
                {
                    b.HasOne("IntegraCompanies.Data.Models.ConnectionServer", "ConnectionServer")
                        .WithMany()
                        .HasForeignKey("ConnectionServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectionServer");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.Company", b =>
                {
                    b.Navigation("CompanyMasks");
                });

            modelBuilder.Entity("IntegraCompanies.Data.Models.JurPerson", b =>
                {
                    b.Navigation("Companys");
                });
#pragma warning restore 612, 618
        }
    }
}
